import "./globals.css";
import Header from "@/components/header/Header";
import { Providers } from "./providers";
import { fonts } from "./fonts";
// export const runtime = "edge";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Y-Typing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={fonts.rubik.variable}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
