// { k: "0", r: ["0"] },
// { k: "1", r: ["1"] },
// { k: "2", r: ["2"] },
// { k: "3", r: ["3"] },
// { k: "4", r: ["4"] },
// { k: "5", r: ["5"] },
// { k: "6", r: ["6"] },
// { k: "7", r: ["7"] },
// { k: "8", r: ["8"] },
// { k: "9", r: ["9"] },

export const ROMA_MAP = [
  { k: "ぎゃ", r: ["gya", "gilya", "gixya"] },
  { k: "ぎぃ", r: ["gyi", "gili", "gixi", "gilyi", "gixyi"] },
  { k: "ぎゅ", r: ["gyu", "gilyu", "gixyu"] },
  { k: "ぎぇ", r: ["gye", "gile", "gixe", "gilye", "gixye"] },
  { k: "ぎょ", r: ["gyo", "gilyo", "gixyo"] },
  { k: "きゃ", r: ["kya", "kilya", "kixya"] },
  { k: "きぃ", r: ["kyi", "kili", "kixi", "kilyi", "kixyi"] },
  { k: "きゅ", r: ["kyu", "kilyu", "kixyu"] },
  { k: "きぇ", r: ["kye", "kile", "kixe", "kilye", "kixye"] },
  { k: "きょ", r: ["kyo", "kilyo", "kixyo"] },
  { k: "ぐぁ", r: ["gwa", "gula", "guxa"] },
  { k: "ぐぃ", r: ["gwi", "guli", "guxi", "gulyi", "guxyi"] },
  { k: "ぐぅ", r: ["gwu", "gulu", "guxu"] },
  { k: "ぐぇ", r: ["gwe", "gule", "guxe", "gulye", "guxye"] },
  { k: "ぐぉ", r: ["gwo", "gulo", "guxo"] },
  { k: "しゃ", r: ["sya", "sha", "silya", "sixya", "shilya", "shixya", "cilya", "cixya"] },
  {
    k: "しぃ",
    r: [
      "syi",
      "sili",
      "sixi",
      "silyi",
      "shixyi",
      "shili",
      "shixi",
      "shilyi",
      "shixyi",
      "cili",
      "cixi",
      "cilyi",
      "cixyi",
    ],
  },
  { k: "しゅ", r: ["syu", "shu", "silyu", "sixyu", "shilyu", "shixyu", "cilyu", "cixyu"] },
  {
    k: "しぇ",
    r: [
      "sye",
      "she",
      "sile",
      "sixe",
      "silye",
      "sixye",
      "shile",
      "shixe",
      "shilye",
      "shixye",
      "cile",
      "cixe",
      "cilye",
      "cixye",
    ],
  },
  { k: "しょ", r: ["syo", "sho", "silyo", "sixyo", "shilyo", "shixyo", "cilyo", "cixyo"] },
  { k: "じゃ", r: ["ja", "zya", "jya", "jilya", "jixya", "zilya", "zixya"] },
  {
    k: "じぃ",
    r: ["zyi", "jyi", "jili", "jixi", "jilyi", "jixyi", "zili", "zixi", "zilyi", "zixyi"],
  },
  { k: "じゅ", r: ["ju", "zyu", "jyu", "jilyu", "jixyu", "zilyu", "zixyu"] },
  {
    k: "じぇ",
    r: ["je", "zye", "jye", "jile", "jixe", "jilye", "jixye", "zile", "zixe", "zilye", "zixye"],
  },
  { k: "じょ", r: ["jo", "zyo", "jyo", "jilyo", "jixyo", "zilyo", "zixyo"] },
  { k: "すぁ", r: ["swa", "sula", "suxa"] },
  { k: "すぃ", r: ["swi", "suli", "suxi", "sulyi", "suxyi"] },
  { k: "すぅ", r: ["swu", "sulu", "suxu"] },
  { k: "すぇ", r: ["swe", "sule", "suxe", "sulye", "suxye"] },
  { k: "すぉ", r: ["swo", "sulo", "suxo"] },
  { k: "ちゃ", r: ["tya", "cya", "cha", "tilya", "tixya", "chilya", "chixya"] },
  {
    k: "ちぃ",
    r: ["tyi", "cyi", "tili", "tixi", "tilyi", "tixyi", "chili", "chixi", "chilyi", "chixyi"],
  },
  { k: "ちゅ", r: ["tyu", "cyu", "chu", "tilyu", "tixyu", "chilyu", "chixyu"] },
  {
    k: "ちぇ",
    r: [
      "tye",
      "cye",
      "che",
      "tile",
      "tixe",
      "tilye",
      "tixye",
      "chile",
      "chixe",
      "chilye",
      "chixye",
    ],
  },
  { k: "ちょ", r: ["tyo", "cyo", "cho", "tilyo", "tixyo", "chilyo", "chixyo"] },
  { k: "ぢゃ", r: ["dya", "dilya", "dixya"] },
  { k: "ぢぃ", r: ["dyi", "dili", "dixi", "dilyi", "dixyi"] },
  { k: "ぢゅ", r: ["dyu", "dilyu", "dixyu"] },
  { k: "ぢぇ", r: ["dye", "dile", "dixe", "dilye", "dixye"] },
  { k: "ぢょ", r: ["dyo", "dilyo", "dixyo"] },
  { k: "つぁ", r: ["tsa", "tula", "tuxa", "tsula", "tsuxa"] },
  { k: "つぃ", r: ["tsi", "tuli", "tuxi", "tulyi", "tuxyi", "tsuli", "tsuxi", "tsulyi", "tsuxyi"] },
  { k: "つぇ", r: ["tse", "tule", "tuxe", "tulye", "tuxye", "tsule", "tsuxe", "tsulye", "tsuxye"] },
  { k: "つぉ", r: ["tso", "tulo", "tuxo", "tsulo", "tsuxo"] },
  { k: "てゃ", r: ["tha", "telya", "texya"] },
  { k: "てぃ", r: ["thi", "t'i", "teli", "texi", "telyi", "texyi"] },
  { k: "てゅ", r: ["thu", "t'yu", "telyu", "texyu"] },
  { k: "てぇ", r: ["the", "tele", "texe", "telye", "texye"] },
  { k: "てょ", r: ["tho", "telyo", "texyo"] },
  { k: "でゃ", r: ["dha", "delya", "dexya"] },
  { k: "でぃ", r: ["dhi", "d'i", "deli", "dexi", "delyi", "dexyi"] },
  { k: "でゅ", r: ["dhu", "d'yu", "delyu", "dexyu"] },
  { k: "でぇ", r: ["dhe", "dele", "dexe", "delye", "dexye"] },
  { k: "でょ", r: ["dho", "delyo", "dexyo"] },
  { k: "とぁ", r: ["twa", "tola", "toxa"] },
  { k: "とぃ", r: ["twi", "toli", "toxi", "tolyi", "toxyi"] },
  { k: "とぅ", r: ["twu", "t'u", "tolu", "toxu"] },
  { k: "とぇ", r: ["twe", "tole", "toxe", "tolye", "toxye"] },
  { k: "とぉ", r: ["two", "tolo", "toxo"] },
  { k: "どぁ", r: ["dwa", "dola", "doxa"] },
  { k: "どぃ", r: ["dwi", "doli", "doxi", "dolyi", "doxyi"] },
  { k: "どぅ", r: ["dwu", "d'u", "dolu", "doxu"] },
  { k: "どぇ", r: ["dwe", "dole", "doxe", "dolye", "doxye"] },
  { k: "どぉ", r: ["dwo", "dolo", "doxo"] },
  { k: "にゃ", r: ["nya", "nilya", "nixya"] },
  { k: "にぃ", r: ["nyi", "nili", "nixi", "nilyi", "nixyi"] },
  { k: "にゅ", r: ["nyu", "nilyu", "nixyu"] },
  { k: "にぇ", r: ["nye", "nile", "nixe", "nilye", "nixye"] },
  { k: "にょ", r: ["nyo", "nilyo", "nixyo"] },
  { k: "ひゃ", r: ["hya", "hilya", "hixya"] },
  { k: "ひぃ", r: ["hyi", "hili", "hixi", "hilyi", "hixyi"] },
  { k: "ひゅ", r: ["hyu", "hilyu", "hixyu"] },
  { k: "ひぇ", r: ["hye", "hile", "hixe", "hilye", "hixye"] },
  { k: "ひょ", r: ["hyo", "hilyo", "hixyo"] },
  { k: "ぴゃ", r: ["pya", "pilya", "pixya"] },
  { k: "ぴぃ", r: ["pyi", "pili", "pixi", "pilyi", "pixyi"] },
  { k: "ぴゅ", r: ["pyu", "pilyu", "pixyu"] },
  { k: "ぴぇ", r: ["pye", "pile", "pixe", "pilye", "pixye"] },
  { k: "ぴょ", r: ["pyo", "pilyo", "pixyo"] },
  { k: "びゃ", r: ["bya", "bilya", "bixya"] },
  { k: "びぃ", r: ["byi", "bili", "bixi", "bilyi", "bixyi"] },
  { k: "びゅ", r: ["byu", "bilyu", "bixyu"] },
  { k: "びぇ", r: ["bye", "bile", "bixe", "bilye", "bixye"] },
  { k: "びょ", r: ["byo", "bilyo", "bixyo"] },
  { k: "ゔぁ", r: ["va", "vula", "vuxa"] },
  { k: "ゔぃ", r: ["vi", "vyi", "vuli", "vuxi", "vulyi", "vuxyi"] },
  { k: "ゔぇ", r: ["ve", "vye", "vule", "vuxe", "vulye", "vuxye"] },
  { k: "ゔぉ", r: ["vo", "vulo", "vuxo"] },
  { k: "ゔゃ", r: ["vya", "vulya", "vuxya"] },
  { k: "ゔゅ", r: ["vyu", "vulyu", "vuxyu"] },
  { k: "ゔょ", r: ["vyo", "vulyo", "vuxyo"] },
  { k: "ふぁ", r: ["fa", "fwa", "hwa", "fula", "fuxa", "hula", "huxa"] },
  {
    k: "ふぃ",
    r: ["fi", "fwi", "hwi", "fuli", "fuxi", "fulyi", "fuxyi", "huli", "huxi", "hulyi", "huxyi"],
  },
  { k: "ふぅ", r: ["fwu", "fulu", "fuxu", "hulu", "huxu"] },
  {
    k: "ふぇ",
    r: [
      "fe",
      "fwe",
      "fye",
      "hwe",
      "fule",
      "fuxe",
      "fulye",
      "fuxye",
      "hule",
      "huxe",
      "hulye",
      "huxye",
    ],
  },
  { k: "ふぉ", r: ["fo", "fwo", "hwo", "fulo", "fuxo", "hulo", "huxo"] },
  { k: "ふゃ", r: ["fya", "fulya", "fuxya", "hulya", "huxya"] },
  { k: "ふゅ", r: ["fyu", "hwyu", "fulyu", "fuxyu", "hulyu", "huxyu"] },
  { k: "ふょ", r: ["fyo", "fulyo", "fuxyo", "hulyo", "huxyo"] },
  { k: "みゃ", r: ["mya", "milya", "mixya"] },
  { k: "みぃ", r: ["myi", "mili", "mixi", "milyi", "mixyi"] },
  { k: "みゅ", r: ["myu", "milyu", "mixyu"] },
  { k: "みぇ", r: ["mye", "mile", "mixe", "milye", "mixye"] },
  { k: "みょ", r: ["myo", "milyo", "mixyo"] },
  { k: "りゃ", r: ["rya", "rilya", "rixya"] },
  { k: "りぃ", r: ["ryi", "rili", "rixi", "rilyi", "rixyi"] },
  { k: "りゅ", r: ["ryu", "rilyu", "rixyu"] },
  { k: "りぇ", r: ["rye", "rile", "rixe", "rilye", "rixye"] },
  { k: "りょ", r: ["ryo", "rilyo", "rixyo"] },
  { k: "いぇ", r: ["ye", "ile", "ixe", "ilye", "ixye", "yile", "yixe", "yilye", "yixye"] },
  { k: "うぁ", r: ["wha", "ula", "uxa", "wula", "wuxa", "whula", "whuxa"] },
  {
    k: "うぃ",
    r: [
      "wi",
      "whi",
      "uli",
      "uxi",
      "ulyi",
      "uxyi",
      "wuli",
      "wuxi",
      "wulyi",
      "wuxyi",
      "whuli",
      "whuxi",
      "whulyi",
      "whuxyi",
    ],
  },
  {
    k: "うぇ",
    r: [
      "we",
      "whe",
      "ule",
      "uxe",
      "ulye",
      "uxye",
      "wule",
      "wuxe",
      "wulye",
      "wuxye",
      "whule",
      "whuxe",
      "whulye",
      "whuxye",
    ],
  },
  { k: "うぉ", r: ["who", "ulo", "uxo", "wulo", "wuxo", "whulo", "whuxo"] },
  { k: "くぁ", r: ["qa", "qwa", "kwa", "kula", "kuxa", "qula", "quxa", "cula", "cuxa"] },
  {
    k: "くぃ",
    r: [
      "qi",
      "qwi",
      "qyi",
      "kwi",
      "kuli",
      "kuxi",
      "kulyi",
      "kuxyi",
      "quli",
      "quxi",
      "qulyi",
      "quxyi",
      "culi",
      "cuxi",
      "culyi",
      "cuxyi",
    ],
  },
  { k: "くぅ", r: ["qwu", "kwu", "kulu", "kuxu", "qulu", "quxu", "culu", "cuxu"] },
  {
    k: "くぇ",
    r: [
      "qe",
      "qwe",
      "qye",
      "kwe",
      "kule",
      "kuxe",
      "kulye",
      "kuxye",
      "qule",
      "quxe",
      "qulye",
      "quxye",
      "cule",
      "cuxe",
      "culye",
      "cuxye",
    ],
  },
  { k: "くぉ", r: ["qo", "qwo", "kwo", "kulo", "kuxo", "qulo", "quxo", "culo", "cuxo"] },
  { k: "くゃ", r: ["qya", "kulya", "kuxya", "qulya", "quxya", "culya", "cuxya"] },
  { k: "くゅ", r: ["qyu", "kulyu", "kuxyu", "qulyu", "quxyu", "culyu", "cuxyu"] },
  { k: "くょ", r: ["qyo", "kulyo", "kuxyo", "qulyo", "quxyo", "culyo", "cuxyo"] },
  { k: "あ", r: ["a"] },
  { k: "い", r: ["i", "yi"] },
  { k: "う", r: ["u", "wu", "whu"] },
  { k: "え", r: ["e"] },
  { k: "お", r: ["o"] },
  { k: "か", r: ["ka", "ca"] },
  { k: "き", r: ["ki"] },
  { k: "く", r: ["ku", "cu", "qu"] },
  { k: "け", r: ["ke"] },
  { k: "こ", r: ["ko", "co"] },
  { k: "さ", r: ["sa"] },
  { k: "し", r: ["si", "ci", "shi"] },
  { k: "す", r: ["su"] },
  { k: "せ", r: ["se", "ce"] },
  { k: "そ", r: ["so"] },
  { k: "た", r: ["ta"] },
  { k: "ち", r: ["ti", "chi"] },
  { k: "つ", r: ["tu", "tsu"] },
  { k: "て", r: ["te"] },
  { k: "と", r: ["to"] },
  { k: "な", r: ["na"] },
  { k: "に", r: ["ni"] },
  { k: "ぬ", r: ["nu"] },
  { k: "ね", r: ["ne"] },
  { k: "の", r: ["no"] },
  { k: "は", r: ["ha"] },
  { k: "ひ", r: ["hi"] },
  { k: "ふ", r: ["hu", "fu"] },
  { k: "へ", r: ["he"] },
  { k: "ほ", r: ["ho"] },
  { k: "ま", r: ["ma"] },
  { k: "み", r: ["mi"] },
  { k: "む", r: ["mu"] },
  { k: "め", r: ["me"] },
  { k: "も", r: ["mo"] },
  { k: "や", r: ["ya"] },
  { k: "ゆ", r: ["yu"] },
  { k: "よ", r: ["yo"] },
  { k: "ら", r: ["ra"] },
  { k: "り", r: ["ri"] },
  { k: "る", r: ["ru"] },
  { k: "れ", r: ["re"] },
  { k: "ろ", r: ["ro"] },
  { k: "わ", r: ["wa"] },
  { k: "を", r: ["wo"] },
  { k: "ん", r: ["n", "xn"] }, // nn, n'はワード生成時に追加される。
  { k: "ゔ", r: ["vu"] },
  { k: "が", r: ["ga"] },
  { k: "ぎ", r: ["gi"] },
  { k: "ぐ", r: ["gu"] },
  { k: "げ", r: ["ge"] },
  { k: "ご", r: ["go"] },
  { k: "ざ", r: ["za"] },
  { k: "じ", r: ["zi", "ji"] },
  { k: "ず", r: ["zu"] },
  { k: "ぜ", r: ["ze"] },
  { k: "ぞ", r: ["zo"] },
  { k: "だ", r: ["da"] },
  { k: "ぢ", r: ["di"] },
  { k: "づ", r: ["du"] },
  { k: "で", r: ["de"] },
  { k: "ど", r: ["do"] },
  { k: "ば", r: ["ba"] },
  { k: "び", r: ["bi"] },
  { k: "ぶ", r: ["bu"] },
  { k: "べ", r: ["be"] },
  { k: "ぼ", r: ["bo"] },
  { k: "ぱ", r: ["pa"] },
  { k: "ぴ", r: ["pi"] },
  { k: "ぷ", r: ["pu"] },
  { k: "ぺ", r: ["pe"] },
  { k: "ぽ", r: ["po"] },
  { k: "ぁ", r: ["xa", "la"] },
  { k: "ぃ", r: ["xi", "li", "lyi", "xyi"] },
  { k: "ぅ", r: ["xu", "lu"] },
  { k: "ぇ", r: ["xe", "le", "lye", "xye"] },
  { k: "ぉ", r: ["xo", "lo"] },
  { k: "ゃ", r: ["xya", "lya"] },
  { k: "ゅ", r: ["xyu", "lyu"] },
  { k: "ょ", r: ["xyo", "lyo"] },
  { k: "ゎ", r: ["xwa", "lwa"] },
  { k: "っ", r: ["xtu", "ltu", "xtsu", "ltsu"] },
  { k: "ヵ", r: ["xka", "lka"] },
  { k: "ヶ", r: ["xke", "lke"] },
  { k: "←", r: ["zh"] },
  { k: "↓", r: ["zj"] },
  { k: "↑", r: ["zk"] },
  { k: "→", r: ["zl"] },
  { k: "『", r: ["z["] },
  { k: "』", r: ["z]"] },
  { k: "ヰ", r: ["wyi"] },
  { k: "ゐ", r: ["wyi"] },
  { k: "ヱ", r: ["wye"] },
  { k: "ゑ", r: ["wye"] },
  { k: "ー", r: ["-"] },
  { k: "～", r: ["~", "z-"] },
  { k: "~", r: ["~", "z-"] },
  { k: "、", r: [","] },
  { k: "。", r: ["."] },
  { k: "・", r: ["/", "z/"] },
  { k: "”", r: ['"'] },
  { k: "“", r: ['"'] },
  { k: "’", r: ["'"] },
  { k: "￥", r: ["\\"] },
  { k: "「", r: ["["] },
  { k: "」", r: ["]"] },
];
